import {Store,Goodgoods,Shopping,Worldwide,Member,Login,Register,SelectStore,Discount,Essence,Active,Makeup,Home,Healthcare,Infant,National} from "../pages"

export const TabBarRoute = [
    {
        path:"/store",
        component:Store,
        meta:{
            flag:true,
        },
        text:"逛商场",
        icon:"\ue612",
        children:[
            {
                path:"/store/selectStore",
                component:SelectStore,
                meta:{
                    flag:false
                },
            }
        ],

    },
    {
        path:"/goodgoods",
        component:Goodgoods,
        meta:{
            flag:true,
        },
        text:"好物圈",
        icon:"\ue761",
    },
    {
        path:"/shopping",
        component:Shopping,
        meta:{
            flag:true,
        },
        text:"购物",
        icon:"\ue784",
    },
    {
        path:"/worldwide",
        component:Worldwide,
        meta:{
            flag:true,
        },
        text:"海外购",
        icon:"\ue624",
        children:[
            {
                path:"/worldwide/discount",
                component:Discount,
                meta:{
                    flag:true,
                }
            },
            {
                path:"/worldwide/essence",
                component:Essence,
                meta:{
                    flag:true,
                }
            },
            {
                path:"/worldwide/active",
                component:Active,
                meta:{
                    flag:true,
                }
            },
            {
                path:"/worldwide/makeup",
                component:Makeup,
                meta:{
                    flag:true,
                }
            },
            {
                path:"/worldwide/home",
                component:Home,
                meta:{
                    flag:true,
                }
            },
            {
                path:"/worldwide/healthcare",
                component:Healthcare,
                meta:{
                    flag:true,
                }
            },
            {
                path:"/worldwide/infant",
                component:Infant,
                meta:{
                    flag:true,
                }
            },
            {
                path:"/worldwide/national",
                component:National,
                meta:{
                    flag:true,
                }
            },
        ],
    },
    {
        path:"/member",
        component:Member,
        meta:{
            flag:true,
        },
        text:"我的",
        icon:"\ue635",
    }
]

export const NotTabBarRoute = [
    {
        path:"/login",
        component:Login
    },
    {
        path:"/register",
        component:Register
    }
]

export const configRoute = TabBarRoute.concat(NotTabBarRoute);